removing Windows CRLF char
kbaseapps/ReadsUtils pull request #65
Opened 2020-02-28 19:59 UTC by Tianhao-Gu

2020-02-28 20:49 UTC, MrCreosote commented
This seems like a weird thing to have to fix manually. I'd assume there's some way to get python to automatically convert windows line feeds to unix - have you looked into that?

2020-02-28 20:50 UTC, MrCreosote commented
Might be useful: https://stackoverflow.com/a/2717154/643675

2020-02-28 20:53 UTC, MrCreosote commented
maybe just ditch the check then fix optimization and just always run it through the fix loop with the python line converter

2020-02-28 20:55 UTC, Tianhao-Gu commented
@MrCreosote Yea. Python `open(file_path)` can handle it just fine. But it's the 3rd party validator that throws an error:
https://github.com/kbaseapps/ReadsUtils/blob/master/lib/ReadsUtils/ReadsUtilsImpl.py#L895-L897

2020-02-28 20:59 UTC, MrCreosote commented
that's why I'm saying to always run the fix loop, so you always remove blank lines and windows LF chars. Doing that is probably a whole lot faster than downloading the file so I doubt it'll add much time to the overall process

2020-02-28 20:59 UTC, MrCreosote commented
Should probably file a bug with the 3rd party dev too

2020-02-28 21:21 UTC, Tianhao-Gu commented
@MrCreosote sure. Just update code to always run fix loop.

2020-02-28 23:41 UTC, MrCreosote requested changes
LGTM other than 1 thing

2020-02-28 23:41 UTC, MrCreosote commented on kbase.yml
>      [gaprice, msneddon, jkbaumohl]
Add yourself

2020-02-29 00:08 UTC, sean-mccorkle reviewed
This is not a show stopper, but if it were me, I would rename the function ValidateFASTQ to ValidateAndCleanFASTQ since its doing some cleanup on the file as well.

Also (again) not a show stopper:   I know FASTA files were not included in this, and I don't know of any occurrences of ^M's in FASTA files being reported, but is it worth considering checking those as well for this condition?  Or should that wait for an actual occurrence to be reported?

2020-02-29 00:08 UTC, sean-mccorkle commented on lib/ReadsUtils/ReadsUtilsImpl.py
> +                    mode='w', dir=self.scratch) as t:
I think this is a big improvement in the code

2020-02-29 00:24 UTC, MrCreosote commented
> This is not a show stopper, but if it were me, I would rename the function ValidateFASTQ to ValidateAndCleanFASTQ since its doing some cleanup on the file as well.

It's not really though - it's making a temporary file with an arbitrary name and making the changes there and discarding it when done. It doesn't fix the original file or provide the path to the new file AFIAK.

2020-02-29 00:26 UTC, MrCreosote commented
> This is not a show stopper, but if it were me, I would rename the function ValidateFASTQ to ValidateAndCleanFASTQ

That changes the API, not worth it IMO. Updating the docs would be good.

2020-02-29 02:51 UTC, sean-mccorkle commented
> That changes the API, not worth it IMO. Updating the docs would be good.

That's a good point.  I hadn't realized it was exposed in the spec.

2020-03-01 02:28 UTC, Tianhao-Gu commented
@MrCreosote @sean-mccorkle Thanks guys. Updated doc and added myself as module owner.

2020-03-01 23:03 UTC, MrCreosote approved these changes
Lgtm

2020-03-02 19:27 UTC, merged